certSign = '93:21:9F:C2:73:E2:20:0F:4A:DE:E5:F7:19:1D:C6:56:BA:2A:2D:7B:2F:F5:D2:4C:D5:5C:4B:61:55:00:1E:40'
# secret token hidden in bmp file
secret = ''
appSecret = ''
deviceId = ''
clientId = ''
email = ''
password = ''